"""Add paper summary request model

Revision ID: 0801dc1489ba
Revises: 3e4d28b3d964
Create Date: 2025-03-13 15:40:55.839549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0801dc1489ba'
down_revision: Union[str, None] = '3e4d28b3d964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_summary_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.String(), nullable=False),
    sa.Column('paper_title', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_summary_requests_id'), 'paper_summary_requests', ['id'], unique=False)
    op.create_index(op.f('ix_paper_summary_requests_paper_id'), 'paper_summary_requests', ['paper_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_summary_requests_paper_id'), table_name='paper_summary_requests')
    op.drop_index(op.f('ix_paper_summary_requests_id'), table_name='paper_summary_requests')
    op.drop_table('paper_summary_requests')
    # ### end Alembic commands ###
