"""Add paper summary request model

Revision ID: 65235e3d815d
Revises: 0801dc1489ba
Create Date: 2025-03-13 15:52:23.793624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65235e3d815d'
down_revision: Union[str, None] = '0801dc1489ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_summary_requests', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('paper_summary_requests', sa.Column('error', sa.Text(), nullable=True))
    op.add_column('paper_summary_requests', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.add_column('paper_summary_requests', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('paper_summary_requests', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.alter_column('paper_summary_requests', 'paper_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('paper_summary_requests', 'timestamp')
    op.drop_column('paper_summary_requests', 'success')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_summary_requests', sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('paper_summary_requests', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('paper_summary_requests', 'paper_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('paper_summary_requests', 'completed_at')
    op.drop_column('paper_summary_requests', 'created_at')
    op.drop_column('paper_summary_requests', 'is_completed')
    op.drop_column('paper_summary_requests', 'error')
    op.drop_column('paper_summary_requests', 'summary')
    # ### end Alembic commands ###
